### PR TITLE
Add Primer as HTML files

### PR DESCRIPTION
**Pull request by larsgw**
See https://github.com/tdwg/website/issues/487

A slightly different version is online here: https://larsgw.github.io/tdwg-wiki-archive/SDD/Primer/SddContents.html. The files in this pull request have some manual fixes and a slightly different layout.

### CODE REVIEW

**Review by stanblum — APPROVED** [review]

**Comment by stanblum** [comment]
Hi Lars,

Do you know how to set up GitHub pages for this repo, and are the added
files in the right place to be used that way?

-Stan

**Comment by larsgw** [comment]
Hi Stan,

You can go to Settings → Pages, select "Deploy from a branch", select the "master" branch, and then select the "/docs" directory, where I have added the files. The URL will then be https://tdwg.github.io/sdd/SddContents.html if I am not mistaken.

**Comment by stanblum** [comment]
Hi Lars,

OK, that all worked, and the pages display from the URL you said:
https://tdwg.github.io/sdd/SddContents.html.

I haven't been involved in setting up the websites for various standards,
but I know that TDWG's more widely used standards have their "own"
websites, which involve giving them their own subdomain:

   - https://abcd.tdwg.org/
   - https://ac.tdwg.org/
   - https://dwc.tdwg.org/

There are some nearly-complete draft standards where they've already begun
to develop pages under tdwg.github.io/ :

   - https://tdwg.github.io/hc/
   - https://tdwg.github.io/tcs/  (only a stub; but tcs is nearing
   completion)


All of this highlights some current gaps.  TDWG needs to develop some
consistency in how things transition from development in GitHub, to
well-documented standards under maintenance.  Of course SDD predates our
use of GitHub, but I think I should ask our Infrastructure and Technical
Architecture Group if they have any thoughts on how the SDD documentation
should be published.  I will send a note, and maybe open an issue with our
Infrastructure subcommittee.

In the meantime, I think I'll make the simplest edits on the SDD GitHub
landing page so that the Intro/Primer is easily accessible.

With many thanks for your help with this,

-Stan

PS  Do you think there might be a community that could gather in an
interest group for updating SDD or creating a new standard built on top of
more "forward looking" technologies?

**Comment by larsgw** [comment]
> PS  Do you think there might be a community that could gather in an interest group for updating SDD or creating a new standard built on top of more "forward looking" technologies?

I am certainly interested. I know some organizations that have developed their own in-house formats (e.g. the [Norwegian Biodiversity Information Centre](https://github.com/Artsdatabanken/identification_key/blob/master/Data%20format%20(en).md)), who might have input on the standard and interest in using it. I do not know anyone there personally but I could send some emails around to gauge interest.

**Comment by MattBlissett** [comment]
Hi @stanblum,

We (Tim and I) recommend using subdomains of tdwg.org, such as sdd.tdwg.org in this case, wherever possible.  It will allow us to move away from GitHub should that be required in the future, and also looks more official.

GitHub provide redirects for tdwg.github.io/* URLs, so there's no concern of existing links being broken.

**Pull request merged**
